import { chromium } from "playwright";
const b = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--ignore-gpu-blocklist","--enable-unsafe-webgpu"] });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const logs = [];
p.on("console", m => logs.push(`[${m.type()}] ${m.text()}`.slice(0,200)));
p.on("pageerror", e => logs.push(`[pageerror] ${String(e).slice(0,300)}`));
const net = [];
p.on("response", r => { const u=r.url(); if(u.includes(".splat")||u.includes("SplatViewer")||u.match(/\.(js)$/)&&u.includes("Splat")) net.push(`${r.status()} ${u.split("/").pop()}`); });
await p.goto("https://dslr-app.vercel.app/camera", { waitUntil: "networkidle", timeout: 30000 });
await p.waitForTimeout(6000);
const hasCanvas = await p.locator("canvas").count();
const hasFallbackList = await p.getByText("tap a control below").count();
const hasLoadingText = await p.getByText(/loading 3D/i).count();
const hasControlsHdr = await p.getByText(/^Controls ·/).count();
const bodyText = (await p.locator(".screen").first().innerText().catch(()=>"")).slice(0,300);
await p.screenshot({ path: "/tmp/live-camera.png" });
console.log(JSON.stringify({ hasCanvas, hasFallbackList, hasLoadingText, hasControlsHdr }, null, 1));
console.log("--- NET ---\n" + net.join("\n"));
console.log("--- LOGS ---\n" + logs.slice(0,15).join("\n"));
console.log("--- BODYTEXT ---\n" + bodyText);
await b.close();
